@MiniBank_HostAddress = http://localhost:5043

POST http://localhost:5043/api/customer
Content-Type: application/json

{
  "firstName": "Görkem Ege",
  "lastName": "Zor",
  "email": "ornek@gmail.com",
  "password": "sifre123",
  "birthDate": "2003-05-15"
}
